# Permalinks
permalink:           pretty

# Setup
title:               Tim Wilde
tagline:             'Developer'
description:         "I write code for all sorts of platforms including web, services, mobile, desktop, IoT, etc. This blog is about the things I learn along the way"
url:                 http://timwil.de
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tim Wilde
  url:               https://twitter.com/timwilde
  email:             blog@timwil.de

# Custom vars
contact:
  github:           http://github.com/timwilde
  twitter:          http://twitter.com/timwilde

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-sitemap