# Permalinks
permalink:           pretty

# Setup
title:               Tim Wilde
tagline:             'Developer'
description:         'Polyglot programmer, Azure administrator, container cattleman, and VSTS wrangler-in-training.<br/><br/>I write code for mobile, web, desktop, services, etc.'
url:                 http://timwil.de
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tim Wilde
  url:               https://twitter.com/timwilde
  email:             blog@timwil.de

# Custom vars
version:            0.0.1
contact:
  github:           http://github.com/timwilde
  twitter:          http://twitter.com/timwilde

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-sitemap